"""Pre-facilitator intent classifier.

For every user message that arrives mid- or post-wireframe-render, decide what
the system should DO with it before the facilitator chimes in:

  - tokens   →  pure aesthetic / design-token change (colours, typography).
                Skip the wireframe pipeline entirely. Emit a tokens diff event;
                LiveTokenIframe restyles every screen live, including ones still
                being generated by an in-flight pipeline.
  - cancel   →  scope or direction shift (different feature set, different
                device, different product). Cancel the running main pipeline,
                drop its unfilled skeletons, start a fresh one.
  - edit     →  surgical edit to ONE existing screen ("the dashboard needs a
                sidebar"). Hit /wireframe/edit-screen. Other screens untouched.
  - add      →  additive screens to the existing plan ("also add a billing
                page"). Spawn an additive pipeline alongside the main one,
                no cancellation.
  - none     →  conversational / acknowledgement / clarifying question.
                Facilitator answers; no canvas mutation.

The classifier sees only the user message + a compact canvas summary so it
spends ~50 input tokens per call.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from typing import Any, Literal

from sqlalchemy.ext.asyncio import AsyncSession

from .ai_provider import get_ai_client_for_role

logger = logging.getLogger(__name__)


Route = Literal["tokens", "cancel", "edit", "add", "flow", "arch", "none"]


@dataclass
class IntentResult:
    route: Route
    reason: str = ""
    # tokens route: a partial design_system patch, e.g.
    # {"colors": {"bg": "#fff", "primary": "#1d4ed8"}}
    tokens_patch: dict[str, Any] = field(default_factory=dict)
    # edit route
    target_screen_id: str | None = None
    target_screen_name: str | None = None
    instruction: str = ""
    # add route — list of new screens to append, each a {name, kind, device}
    new_screens: list[dict[str, Any]] = field(default_factory=list)
    # cancel route — short summary of the new direction the next pipeline
    # should pursue (passed to facilitator for context)
    new_direction: str = ""
    # raw model output for debugging
    raw: str = ""


_SYSTEM_PROMPT = """You route user messages in a wireframe-design session into one of these actions. Pick the route that BEST fits the user's intent — pipeline state is informational, NOT a reason to defer.

ABSOLUTE RULE: NEVER clear the canvas. The classifier has SIX routes — `tokens`, `edit`, `add`, `flow`, `arch`, `none`. There is no `cancel` route. ANY user message, even one that sounds like a project pivot ("actually let's redo this for mobile", "scrap that"), must route to `add` if it implies new screens, `edit` if it implies modifying an existing screen, `tokens` if it's a styling change, `flow` / `arch` if it's an explicit user-flow / architecture diagram request. Existing screens on the canvas STAY. The user can manually clear via the Clear Canvas button if they want.

TOKENS APPLY DURING GENERATION: token / palette / typography changes propagate to in-flight wireframes as they finish rendering — they do NOT require existing finished screens. Never return `none` for a colour / font / palette / theme / mood request just because the wireframes are still loading.

- `tokens`: ANY colour / palette / typography / font / contrast / theme adjustment — REQUEST OR STATEMENT OF PREFERENCE. The frontend swaps CSS vars live, so this works whether or not screens are still rendering. Use this whenever the user mentions colours (e.g. "white", "dark", "neutral", "blue accent"), palette, fonts, typography, contrast, theme, brightness, mood ("more professional"), or aesthetic descriptors ("clean", "minimal", "bold", "soft"). A casual statement like "keep the colour scheme mostly white" is a tokens request, not `none` — the user is providing design intent that must be applied to the wireframes.
- `edit`: a surgical change to ONE existing screen / surface — "the dashboard needs a sidebar", "make the settings drawer a full screen instead", "fix the typo on the settings modal", "I meant X" / "change that to Y" referring to something in flight or just placed.
- `add`: ADD new screens to the canvas, leaving everything else alone. This covers the FIRST wireframe brief (empty canvas) AS WELL AS follow-up additions ("also add a billing page", "create the mobile equivalent mockups", "what about a settings drawer"). Whenever the user describes screens that don't yet exist, route to `add`.
- `flow`: user is EXPLICITLY asking to build / map / generate / regenerate / extend a USER FLOW or JOURNEY DIAGRAM. Phrases like "map out the user flow", "build the user flow", "what's the journey?", "show me the flow", "extend the flow with the sign-up path". This route bypasses the wireframe pipeline and runs the flow companion only. Do NOT use for casual mentions of the word "flow" ("the flow of the app feels clunky" is `edit` or `tokens`).
- `arch`: user is EXPLICITLY asking to build / map / generate an ARCHITECTURE / SYSTEM diagram — "show me the architecture", "map the services", "draw the system diagram". Bypasses wireframe, runs the arch generator.
- `none`: PURELY conversational — chit-chat, thanks, generic clarifying questions ("what's Linear?"), acknowledgement. If the user is providing design intent of any kind, do NOT use `none`.

CRITICAL: corrections to a previous turn are NEVER a fresh project. "I meant a full desktop screen" / "actually make that a drawer" / "no, a popover" → that's `edit` of the recently-added surface.

Disambiguation examples:

  [empty canvas] "I'm planning a new admin dashboard with..."  → add (the brief enumerates screens; spawn an additive pipeline to create them)
  "create the mobile equivalent mockups"                       → add (new screens, additive)
  "I meant a full desktop screen, not a drawer"                → edit (correcting the prior addition's kind)
  "actually let's redo this for mobile"                        → add (interpreting as "add mobile versions", since canvas content stays)

You MUST output a single JSON object and nothing else. Schema:

{
  "route": "tokens" | "edit" | "add" | "flow" | "arch" | "none",
  "reason": "<one short sentence>",
  "tokens_patch": { "colors": {...}, "typography": {...} },     // only for tokens
  "target_screen_id": "<id>",                                    // only for edit
  "target_screen_name": "<exact name>",                          // only for edit
  "instruction": "<what to change>",                             // only for edit
  "new_screens": [{ "name": "...", "kind": "screen|modal|drawer|popover", "device": "desktop|mobile|tablet" }]   // only for add
}

Only fill the fields relevant to the chosen route. For unused fields, omit them or leave them empty.

Tokens-patch values must be hex colour strings or font-family names. Common keys: `colors.background`, `colors.foreground`, `colors.primary`, `colors.accent`, `colors.muted`, `typography.fontFamily`, `typography.headingFamily`. If you can't pin a precise value, omit `tokens_patch` and let the route still be `tokens` so the system applies a sensible default.

A wireframe pipeline already running is NOT a reason to return `none`. If the user is making a design ask, route it on its own merit."""


def _summarize_canvas(diagram_state: dict | None) -> str:
    if not diagram_state:
        return "Canvas is empty."
    wf = (diagram_state or {}).get("wireframe") or {}
    screens = wf.get("screens") or []
    if not screens:
        return "Canvas has no wireframes yet."
    lines = []
    for s in screens:
        if not isinstance(s, dict):
            continue
        sid = s.get("id") or "?"
        name = s.get("name") or sid
        kind = s.get("kind") or "screen"
        device = s.get("device") or "desktop"
        lines.append(f"- {sid} · {name} ({kind}, {device})")
    return f"Canvas has {len(lines)} screen(s):\n" + "\n".join(lines)


async def classify_intent(
    user_message: str,
    diagram_state: dict | None,
    *,
    db: AsyncSession,
    has_active_pipeline: bool = False,
    org_id: str | None = None,
) -> IntentResult:
    """Run the classifier. Returns IntentResult; on any failure returns
    route='none' so the system falls back to existing behaviour."""
    if not (user_message or "").strip():
        return IntentResult(route="none", reason="empty message")

    canvas_summary = _summarize_canvas(diagram_state)
    pipeline_state = (
        "A wireframe pipeline is currently running."
        if has_active_pipeline
        else "No wireframe pipeline is currently running."
    )
    user_payload = (
        f"{canvas_summary}\n\n{pipeline_state}\n\n"
        f"User message:\n{user_message.strip()}\n\n"
        "Output the JSON now."
    )

    try:
        ai = await get_ai_client_for_role(org_id=org_id, db=db, role="intent")
        text, in_tok, out_tok = await ai.chat_with_full_usage(
            system=_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_payload}],
            max_tokens=600,
            temperature=0.0,
        )
    except Exception as exc:
        logger.warning("[INTENT] classifier call failed: %s", exc)
        return IntentResult(route="none", reason=f"classifier-error:{exc}")

    parsed = _parse_json(text)
    if not parsed:
        logger.warning("[INTENT] could not parse classifier output: %r", text[:200])
        return IntentResult(route="none", reason="parse-error", raw=text)

    route = parsed.get("route")
    if route not in ("tokens", "cancel", "edit", "add", "flow", "arch", "none"):
        return IntentResult(route="none", reason=f"unknown-route:{route}", raw=text)

    result = IntentResult(
        route=route,  # type: ignore[arg-type]
        reason=str(parsed.get("reason") or ""),
        tokens_patch=parsed.get("tokens_patch") or {},
        target_screen_id=parsed.get("target_screen_id"),
        target_screen_name=parsed.get("target_screen_name"),
        instruction=str(parsed.get("instruction") or ""),
        new_screens=parsed.get("new_screens") or [],
        new_direction=str(parsed.get("new_direction") or ""),
        raw=text,
    )
    logger.info(
        "[INTENT] route=%s reason=%r in_tok=%d out_tok=%d",
        result.route, result.reason[:80], in_tok, out_tok,
    )
    return result


def _parse_json(text: str) -> dict | None:
    """Be lenient — the classifier sometimes wraps JSON in ```json fences."""
    if not text:
        return None
    s = text.strip()
    # strip code fences
    if s.startswith("```"):
        # drop opening fence line
        first_nl = s.find("\n")
        if first_nl > -1:
            s = s[first_nl + 1 :]
        # drop trailing fence
        if s.rstrip().endswith("```"):
            s = s.rstrip()[: -3].rstrip()
    # find first { ... last }
    start = s.find("{")
    end = s.rfind("}")
    if start == -1 or end == -1 or end <= start:
        return None
    try:
        return json.loads(s[start : end + 1])
    except json.JSONDecodeError:
        return None
